### ISSUE TITLE
General: Support for flutter_form_builder 9.0.0

### ISSUE THREAD

**Issue by FXschwartz** [flutter-form-builder-ecosystem/form_builder_phone_field#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

1.4.0

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash
[✓] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
    • Flutter version 3.10.0 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\Preston\AppData\Local\Android\sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: C:\Users\Preston\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\222.4459.24.2221.9971841\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.26)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33529.622
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Users\Preston\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\222.4459.24.2221.9971841
    • Flutter plugin version 73.0.1
    • Dart plugin version 221.6103.1
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at C:\Users\Preston\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • Pixel 4 XL (mobile) • 9B071FFBA003B1 • android-arm64  • Android 13 (API 33)
    • Windows (desktop)   • windows        • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Edge (web)          • edge           • web-javascript • Microsoft Edge 113.0.1774.35

[✓] Network resources
    • All expected network resources are available.

```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

N/A

</details>

### Current Behavior

Updating project to Flutter 3.10 and Dart 3, getting this error when trying to install dependencies
```
Because form_builder_phone_field 1.4.0 depends on flutter_form_builder ^8.0.0 and no versions of form_builder_phone_field match >1.4.0 <2.0.0, form_builder_phone_field ^1.4.0 requires flutter_form_builder ^8.0.0.
So, because level_tap depends on both flutter_form_builder ^9.0.0 and form_builder_phone_field ^1.4.0, version solving failed.
```

### Expected Behavior

Should install dependencies with no errors

### Steps To Reproduce

1. Create new project with Flutter 3.10 and Dart 3
2. Add the following dependencies to the pubspec.yaml
```
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  form_builder_phone_field: ^1.4.0
```
3. Run `flutter pub get`

**Comment by deandreamatias** [comment]
Hi!
Thanks for report.
Maybe I will update this on sunday

**Comment by MonkeyDrone** [comment]
Looking forward to the update so I can update my project. Thank you!

**Comment by FXschwartz** [comment]
> Hi!
> Thanks for report.
> Maybe I will update this on sunday

I went ahead and forked the repo just to get my project updated and am happy to creat a PR.

But it looks like the decoration property was removed from the inherited class.

Should this property now only be something optional that a user can give it? Should it have a default value?

**Comment by deandreamatias** [comment]
> > Hi!
> > Thanks for report.
> > Maybe I will update this on sunday
> 
> I went ahead and forked the repo just to get my project updated and am happy to creat a PR.
> 
> But it looks like the decoration property was removed from the inherited class.
> 
> Should this property now only be something optional that a user can give it? Should it have a default value?

Use FormBuilderFieldDecoration

**Comment by FXschwartz** [comment]
@deandreamatias Looking at this now. Not sure what you mean by using FormBuilderFieldDecoration, as that doesn't seem to exist on the inherited class either.

This is the error on the `super.decoration`

![image](https://github.com/flutter-form-builder-ecosystem/form_builder_phone_field/assets/16527593/21fc184c-6b0b-40ba-a126-19420d62b2ae)

**Comment by deandreamatias** [comment]
Take a look on changelog of flutter_form_builder
Has a breaking change that explain about this

**Comment by deandreamatias** [comment]
I try to update this but need a Mac to accomplish. Maybe on next Tuesday can complete

**Comment by deandreamatias** [comment]
Closed in this commit https://github.com/flutter-form-builder-ecosystem/form_builder_phone_field/commit/203039de9e77080b50c18df521e803573da8fda7
