### ISSUE TITLE
Phone number can't get country value

### ISSUE THREAD

**Issue by SpencerRiddering** [flutter-form-builder-ecosystem/form_builder_phone_field#5]
Some country codes are shared by more than one country. For example, the US and Canada share +1. So, when a user selects a country for their phone number I want to capture and store it so when I display it again, the correct country is selected. 

For example, when a user selects the US as their phone number's country, but if I'm not able to persist that country selection then when I go to display that phone number later I don't know whether it's a US or Canadian phone number so I might show a US flag for a Canadian phone number. 

The issue is that FormBuilderPhoneField's onChanged method does not provide the country that was selected. I believe the issue occurs in the configuration of CountryPickerDialog where the country code is preserved in a private variable, but not propagated forward into the didChange(...) callback:  

```
          onValuePicked: (Country country) {
            setState(() => _selectedDialogCountry = country);
            field.didChange(fullNumber);
          },
```

**Comment by deandreamatias** [comment]
Hi!
Now the Country model has a `regionCode` and a `countryCode`. The regionCode is a IsoCode, like 'US' or 'ES'. The countryCode is the number, like +1 or +34.

I created a pull request to parsing international number by region code. By this way get the right country, even they had the same countryCode
